#ifndef DEVICE_DATA_H_
#define DEVICE_DATA_H_

#define OPENER_DEVICE_VENDOR_ID      44
#define OPENER_DEVICE_TYPE           12
#define OPENER_DEVICE_PRODUCT_CODE   1281
#define OPENER_DEVICE_MAJOR_REVISION 1
#define OPENER_DEVICE_MINOR_REVISION 1
#define OPENER_DEVICE_NAME           "DX200 EtherNet/IP Module"
#define OPENER_DEVICE_SERIAL_NUMBER  0123456789


#endif

